apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    {{- include "maichess.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "maichess"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: maichess-db-secrets
                  key: mongo-password
          ports:
            - containerPort: 27017
              name: tcp
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: tcp
