apiVersion: v1
kind: Secret
metadata:
  name: maichess-app-secrets
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  cookie-domain: {{ .Values.secrets.cookieDomain | quote }}
  cors-origin: {{ .Values.secrets.corsOrigin | quote }}
  topology-ws-url: {{ .Values.secrets.topologyWsUrl | quote }}
  # Constructed connection strings
  postgres-connection-string: {{ printf "Host=postgres;Port=5432;Database=%s;Username=%s;Password=%s" "maichess" "maichess" .Values.secrets.postgresPassword | quote }}
  mongo-connection-string: {{ printf "mongodb://%s:%s@mongo:27017" "maichess" .Values.secrets.mongoPassword | quote }}
  redis-url: {{ printf "redis://:%s@redis-master:6379" .Values.secrets.redisPassword | quote }}
  redis-connection-string: {{ printf "redis-master:6379,password=%s" .Values.secrets.redisPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: maichess-db-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  mongodb-root-password: {{ .Values.secrets.mongoPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-basic-auth-secret
type: Opaque
stringData:
  users: {{ .Values.secrets.prometheusBasicAuthUsers | quote }}
